version: 1
disable_existing_loggers: false
formatters:
  verbose:
    format: "{levelname} {asctime} {module} {message}"
    style: "{"
  simple:
    format: "{levelname} {message}"
    style: "{"
handlers:
  file:
    level: INFO
    class: logging.FileHandler
    filename: debug.log
    formatter: verbose
  console:
    level: INFO
    class: logging.StreamHandler
    formatter: simple
loggers:
  django:
    handlers: [file, console]
    level: INFO
    propagate: true
  myapp:
    handlers: [file, console]
    level: INFO
    propagate: false
